- name: install php
  command: amazon-linux-extras install php7.3 -y
  notify:
    - restart_php

- name: install php modules
  yum:
    name: "{{ php_modules }}"
    state: present
  notify:
    - restart_php
    
- name: start php-fpm
  service:
    name: php-fpm
    state: started

- name: enable php-fpm
  service:
    name:  php-fpm
    enabled: true
  notify:
    - restart_php
    
- name: configure php conf files
  copy:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - php.ini
    - php-fpm.d/www.conf
  notify:
    - restart_php
    
- name: download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer

- name: install composer
  shell: cat /tmp/composer-installer | php -- --install-dir=/usr/local/bin

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer

- name: make composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
