- name: make dir
  file:
    path: /var/www
    state: directory
  
- name: git clone laravel
  shell: |
    git init
    git config core.sparsecheckout true
    git remote add origin https://github.com/wim-web/laravel-load-test.git
    echo /laravel > .git/info/sparse-checkout
    git pull origin master
  args:
    chdir: /var/www