- name: install git
  yum:
    name: git
    
- name: make app dir
  file:
    path: var/www/current
    state: directory
  
- name: git clone
  git:
    clone: yes
    repo: 'https://github.com/wim-web/laravel-load-test.git'
    dest: /var/www/current
    
- composer:
    command: install
    working_dir: /var/www/current/laravel
    
- name: permission log file
  file:
    path: /var/www/current/laravel/storage
    mode: '777'
    recurse: yes
    
- name: copy env
  copy:
    src: .env
    dest: /var/www/current/laravel/.env
  