- composer:
    command: install
    working_dir: /var/www/laravel
    
- name: storage permission
  file:
    path: /var/www/laravel/storage
    mode: '777'
    recurse: yes
    group: nginx
    
- name: cache permission
  file:
    path: /var/www/laravel/bootstrap/cache
    mode: '777'
    recurse: yes
    group: nginx
    
- name: copy env
  copy:
    src: .env
    dest: /var/www/laravel/.env
    
- name: generate key
  shell:
    php artisan key:generate
  args:
    chdir: /var/www/laravel
    
- name: cache config
  shell:
    php artisan config:cache
  args:
    chdir: /var/www/laravel
    
- name: cache route
  shell:
    php artisan route:cache
  args:
    chdir: /var/www/laravel
    
- name: optimize composer
  shell:
    composer install --optimize-autoloader --no-dev
  args:
    chdir: /var/www/laravel
    
- name: restart_php
  service:
    name:  php-fpm
    state: restarted
    
  